name: "Pull Request Labeler"
on:
  schedule:
  - cron: "*/6 * * * *"

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: fjeremic/cron-labeler@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
